config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root                    "static_pages#home"
  get    '/help',     to: "static_pages#help"
  get    '/about',    to: "static_pages#about"
  get    '/signup',   to: "users#new"
  get    '/login',    to: "sessions#new"
  post   '/login',    to: "sessions#create"
  get    '/logout',   to: "sessions#destroy" # For some reason, delete not working
  
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to Quick Reads!"
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "QuickReads"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    reset_session
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<nav>
  <ul>
    <li><%= link_to "About",  about_path %></li>
    <li><%= link_to "Help",   help_path %></li>
    <li><a href="https://github.com/davidomullan/quickReads">Repository</a></li>
  </ul>
</nav>

app/views/layouts/_header.html.erb
<div class="logo">
  <%= link_to image_tag "Quick_Reads_Logo_Square.png" %>
</div>
<div class="title">
  <h1>Quick Reads</h1>
</div>
<nav>
  <ul>
    <li><%= link_to "Home",     root_path %></li>
    <li><%= link_to "Discover", root_path %></li>
    <li><%= link_to "Create",   root_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Users", '#' %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", '#' %></li>
      <li>
        <%= link_to "Log out", logout_path,
                               data: { "turbo-method": :delete } %>
      </li>
    <% else %>
      <li><%= link_to "Log in",   login_path %></li>
      <li><%= link_to "Sign up",  signup_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta chartset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div class="content">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>Quick Reads About Page</h1>
<p>This site was designed to get people reading again!</p>
<p>
  There are so many great stories out there, and the best way
  to know what you like is to read as much as possible. Short
  stories present a low bar to admission! Flip through stories
  until you find what you like!
</p>

<h2>
  Founder: David M O'Mullan
</h2>
<p>
  Learn more about me 
  <a href="https://www.davidomullan.com">here</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Quick Reads Help Page</h1>
<p>
  If you have any questions, generate an issue on
  <a href="https://github.com/davidomullan/quickReads/issues">GitHub</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Welcome to Quick Reads!</h1>
<p>Flip through short stories to your hearts desire!</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<%= form_with(model: @user) do |f| %>
  <%= render 'shared/error_messages' %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>